### ISSUE TITLE
Definitie van Object opnemen in modelleerprincipes

### ISSUE THREAD

**Issue by pmaria** [Geonovum/disgeo-imsor#1]
TODO herschrijven:

Nog geen definitie kunnen vinden in kader van DisGeo

**NEN3610:2011**:
“Het toepassingsgebied beperkt zich tot informatieobjecten met informatie over een directe of indirecte locatie ten opzichte van de aarde (geo-informatie).”

**MIM**:
“Een ding, een tastbaar iets, in de werkelijkheid, zoals daarnaar gekeken wordt vanuit een bepaald domein.
Issue hier: dit is IMO te restrictief; er zijn ook niet tastbare objecten die ik als object wil beschouwen.

**Comment by lvdbrink** [comment]
TODO: Een discussie op gang brengen met de NEN3610 werkgroep over de definitie van Object.

**Comment by RiX012** [comment]
Volgens mij het lastige in dezen is dat twee van de belangrijkste contexten waarin de term Object kan worden beschouwd (de reële wereld en de informatica) in dit project een beetje door elkaar lopen. Een 'ObjectTypeLibrary' waar iedereen het tegenwoordig over heeft gaat ook niet alleen over de Objecten die hier bedoeld worden. Wellicht dat de term 'Concept' hier uitkomst kan bieden? Uiteraard kan het 'Kenobject' (uit de filosofie) ook uitkomst bieden.

**Comment by pmaria** [comment]
@RiX012 'Kenobject' kende ik nog niet, maar dekt zeker de lading. Dank daarvoor, dat kunnen we gebruiken.

Het lastige van het woord 'Concept' is dat deze ook als synoniem voor 'Begrip' wordt gebruikt. Daarnaast, gezien we ook met linked data bezig gaan, is een instantie van skos:Concept iets anders dan een instantie van rdfs:Class. Maar, op zich sta ik er open voor om 'Concept' te hanteren, zolang we het maar duidelijk definiëren.

**Comment by RiX012** [comment]
Ja eens. Bij een goede definitie maakt het eigenlijk niet uit welke term je kiest.

**Comment by mickbaggen** [comment]
In de NEN 2660-1 hanteren we de volgende definitie voor Object: "entiteit die bestaat of kan bestaan binnen een concrete ruimte-tijd. Een object voert activiteiten uit en wordt getransformeerd door een activiteit."

**Comment by PalmJanssen** [comment]
De aangepaste termen in NEN 3610 zijn nu deze:

**Ding/Object** 
De werkelijkheid bestaat in al zijn complexiteit. Deze werkelijkheid wordt door mensen waargenomen door zeis opgebouwd uit individuele objecten (real world objects) op te bouwen. Synoniem voor 'Object' is 'Ding'. Een object of een ding is een individueel fenomeen in de werkelijkheid. Bijvoorbeeld een specifiek gebouw, een specifiek bos, een specifieke boom. Het gaat hierbij om de individuele voorkomens en niet om een type-classificatie. 

Eigenschappen van dingen worden beschreven door kenmerken. Een boom heeft bijvoorbeeld een hoogte, een stam, wortels, een stamdiameter en allerlei andere kenmerken die deze boom onderscheiden van andere bomen en andere dingen. 

**Concept/Begrip** 
Een concept of begrip is de mentale voorstelling van een ding of kenmerk van een ding in de werkelijkheid. Het beschrijft de gedachte bij een ding of een kenmerk van een ding. Concepten horen dus zowel bij dingen als bij kenmerken van dingen. Het beantwoord de vraag wat iets is. Wat is een boom? Wat is een hoogte? Deze gedachte is geformaliseerd in een definitie. 

Een concept of een begrip gaat niet meer over de individuele objecten maar classificeert objecten die bij elkaar horen tot één concept. Een specifieke boom behoort nu tot het 'algemene' concept boom: 'een houtig gewas met wortels, een duidelijk onderscheiden stam en kroon'. 

**Symbool/Term** 
Om over de mentale voorstelling te kunnen praten is er een woord of term nodig. Het woord of een term symboliseert daarmee het concept. Je kan er dan over praten. Het woord wordt tevens gebruikt om het ding in de werkelijkheid te benoemen. "Ah, een boom." 

**Begrippenmodel/taxonomie** 
Bij een begrippenmodel of taxonomie gaat het niet meer om individuele dingen, maar om begrippen waarmee individuele dingen getypeerd (geclassificeerd) kunnen worden. Een begrippenmodel beschrijft de werkelijkheid dus niet in directe zin. Een concept is dan niet meer een individueel ding maar een groep van dingen die onder eenzelfde mentale voorstelling vallen. Een concept wordt gesymboliseerd door een term en gedefinieerd door een definitie in taal. 

**Informatiemodel** 
Een informatiemodel beschrijft een ander abstractieniveau dan een begrippenmodel. Het beschrijft de werkelijkheid in termen van gegevens op een detailniveau dat nodig voor de toepassing van het model. Objecten uit de werkelijkheid met dezelfde eigenschappen worden in het model gerepresenteerd of benoemd door een objecttype. Kenmerken van objecten worden gerepresenteerd door attributen die bij het objecttype horen of door relaties tussen objecttypenobjecten. Zo heeft bijvoorbeeld het objecttype Gebouw een attribuut bouwhoogte en een relatie eigendom van met een objecttype Persoon in de rol van eigenaar. 

Objecttypen, attributen en relaties kunnen één op één overeenkomen met concepten maar meestal wordt het informatiemodel apart gehouden van het begrippenmodel. De begrippen zijn daarbij de formalisering van de betekenis van de objecttypen, attributen en relaties. Het informatiemodel definieert de gegevensstructuur die nodig is om de werkelijkheid door middel van gegevens te representeren. Om objecttypen, attributen en relaties aan concepten te verbinden zijn er in het informatiemodel verwijzingen opgenomen naar het overeenkomstige concept. 

Een **informatieobject** is een op zichzelf staand geheel van gegevens met een eigen identiteit (NEN 2660, NTA 8035). In de context van een objecttype is het één voorkomen (instantie) van een objecttype en representeert een specifiek object/ding in de werkelijkheid. Een object/ding in de werkelijkheid wordt dus gerepresenteerd door een informatieobject conform het informatiemodel.

**Comment by lvdbrink** [comment]
In het Modelleerprincipes document staat momenteel wel een (soort van) definitie van (geo)informatieobject, maar niet van Object. Deze opnemen.

**Comment by lvdbrink** [comment]
Definitie van Object is opgenomen, zie 1fd48db.
