### ISSUE TITLE
Idee voor een modelleerprincipe gebaseerd op 'priority of constituencies'

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/disgeo-imsor#13]
In het [Web Platform Design Principles](https://w3ctag.github.io/design-principles/) document staat een mooi principe [Put user needs first (Priority of Constituencies)](https://w3ctag.github.io/design-principles/#priority-of-constituencies). 

> User needs come before the needs of web page authors, which come before than the needs of user agent implementors, which come before than the needs of specification writers, which come before theoretical purity.

Als wij kunnen definieren voor wie ons informatiemodel is, kunnen we een soortgelijk principe definiëren. We hebben het af en toe over 'dingen zuiver modelleren'. Dat is zoiets als 'theoretical purity' in het lijstje hierboven. Niet onbelangrijk, maar moet lagere prioriteit hebben dan andere belangen. Welke belangen zijn dit? Als we dit helder kunnen formuleren, kan ons dit helpen bij het nemen van beargumenteerde ontwerpbeslissingen.

**Comment by RiX012** [comment]
Lijkt me een goed uitgangspunt, zolang het niet ten koste gaat van de vastlegging van de semantiek. Ik zie vaak dat er shortcuts genomen worden door bestaande/gekende modelleerconstructies en/of ontologieen te 'misbruiken'. Dit zou niet goed zijn.
Ook hier weer belangrijk om de 'ontwerpbeslissing' dan vast te leggen.

**Comment by lvdbrink** [comment]
Ik zat hier nog eens over na te denken. De stakeholders die ze in web platform design principles hanteren kun je als volgt vertalen naar onze situatie: 

- User needs > **eindgebruikers**
- needs of web page authors > **data gebruikers** (web app bouwers, data journalisten, datawetenschappers)
- needs of user agent implementers > **softwareleveranciers**
- needs of specification writers > **informatiemodelleurs**
- theoretical purity > **zuiver modelleren**

De vraag is nu kan dit ons misschien helpen, bijvoorbeeld bij het kiezen tussen de uitwerkingen van metadata op attribuutniveau? (#14)

**Comment by lvdbrink** [comment]
Aanvullend, doelgroepen uit Beleidsvisie: 
- Overheidsgebruikers,   die verplicht gebruik dienen te maken van de geo-basisregistraties voor hun   processen
- Open   data gebruikers, zoals bedrijven die waarde toevoegen aan gegevens in de   basisregistraties en nieuwe producten ontwikkelen.
- Eindgebruikers   van de informatie, zoals burgers en bedrijven.

**Comment by lvdbrink** [comment]
Is doorgevoerd in concept modelleerprincipes. Deze moeten nog besproken worden, maar dat is weer een ander issue.
