### ISSUE TITLE
Identificatie / Levensloop object

### ISSUE THREAD

**Issue by pmaria** [Geonovum/disgeo-imsor#2]
TODO herschrijven

> “Objecten worden in de SOR opgenomen op het moment dat deze volgens de voor het betreffende objecttype gedefinieerde criteria ontstaan en blijven daarna altijd in de registratie aanwezig, waarbij voor elk objecttype is vastgelegd welke levensfasen in de vastlegging van een object worden onderscheiden.”

Het is van belang dat registraties dezelfde criteria hanteren voor identificatie en levensloop van objecten. 

Anders wordt samenhang lastig

**Comment by lvdbrink** [comment]
Deze overweging nemen we mee in het informatiemodel bij het modelleren van het generieke onderwerp Levensloop #15.
