### ISSUE TITLE
Principe opnemen over scheiden meta-eigenschappen van directe eigenschappen

### ISSUE THREAD

**Issue by pmaria** [Geonovum/disgeo-imsor#3]
TODO herschrijven

Om een SOR te bevorderen is het van belang om metaeigenschappen te scheiden van directe eigenschappen.

Met directe eigenschappen wordt bedoeld, eigenschappen die essentieel onderdeel zijn van het ding.

Wanneer metaeigenschappen als directe eigenschappen van van objecten worden gemodelleerd levert dit problemen op in het 
relateren/gelijkstellen van objecten tot elkaar.

Metaeigenschappen gaan vaak over registratie van gegevens over objecten; begindatum, einddatum, bron etc.

Is gebouw 123 met begindatum 01-01-2010 en bron Gemeente Amsterdam in de ene registratie wel of niet hetzelfde als gebouw 123 met begindatum 03-05-2012 en bron Provincie Noord-Holland?

Compatibiliteit linked data en andere graaf gebaseerde informatiestrategieen.
Linked data gebruikt URIs voor de identificatie van non-informatieobjecten. 

**Oplossingsrichting**:
Introduceer nieuw object `Objectregistratie`: Dit object wordt de houder van de metaeigenschappen.
Elk SOR object heeft een relatie `beschrevenDoor` naar een Objectregistratie object.

**Comment by RiX012** [comment]
Kun je hier wellicht spreken over intrinsieke aspecten vs. extrinsieke aspecten. Bij wijziging van een intrinsieke aspect (eigenschap) zal het object zelf daadwerkelijk veranderen en niet meer hetzelfde zijn. Bij extrinsiek (naam, datum, etc.) veranderd er niets aan het object zelf maar alleen de beschrijving van de kennis over het object.

**Comment by pmaria** [comment]
@RiX012 intrinsiek / extrinsiek dekt niet helemaal de lading. Essentieel eigenlijk ook niet. Wat we eigenlijk bedoelen is dat eigenschappen / predicaten op een object, *direct* over dat object gaan.
De beweegreden hierachter is dat je die kennisuitdrukkingen uit de ene context zou moeten kunnen gebruiken in de andere context, zonder dat je deze moet bewerken. Een voorbeeld: 
```
<gebouw-1>
   <naam> "De Dom"  ;
   <documentnummer> "1234" ;
. 
```

In dit voorbeeld is het aannemelijk dat de `<naam>` van het gebouw zonder veel moeite herbruikbaar is in andere data waarin het gebouw voorkomt, omdat de kennis "direct" gaat over het gebouw.

Gebouw 1 heeft `<documentnummer>`  1234, is vreemd om te zeggen, buiten een context waarin dat begrepen wordt. Dat is omdat `<documentnummer>` niet een "directe" eigenschap is van een gebouw. Het is een "directe" eigenschap van den document, wat op een of andere manier gerelateerd is aan het gebouw. Deze veelvoorkomende manier van informatiemodelleren (denormaliseren) willen we tegengaan, omdat het samenhang lastig maakt.

Ik ben nog op zoek naar een term die hier de lading goed dekt. Voorlopig is "directe eigenschap" het beste wat ik kon bedenken.

**Comment by RiX012** [comment]
Ah ok, ja als je het zo bedoelt dan is intrinsiek / extrinsiek niet de juiste semantiek. Het eigenlijk meer een verschil tussen beschrijvende en omschrijvende eigenschappen lijkt het. Ik denk dat als je de definitie van directe eigenschap maar goed neerzet dat het begrijpelijk is.

**Comment by lvdbrink** [comment]
Volgens mij hebben we dit issue voldoende geadresseerd, klopt dat @pmaria?
- Het Modelleerprincipes doc bevat een principe over directe eigenschappen.
- In onze uitwerkingen modelleren we een Registratieobject.

Zo ja dan kunnen we dit issue sluiten.

**Comment by pmaria** [comment]
Eens. Bij deze.
