### ISSUE TITLE
Duidelijk onderscheidende naamgeving objecten

### ISSUE THREAD

**Issue by pmaria** [Geonovum/disgeo-imsor#4]
TODO herschrijven

Voorbeeld:
bestuurlijke objecttypen

Maak onderscheid tussen de bestuurlijke organisatie en het bestuurlijk gebied / ambtsgebied / grondgebied.

Burgerlijke-Gemeentegebied, Waterschapgebied, Provinciegebied, Rijksgebied, tov Bestuurlijke-Gemeente, Waterschap,  Provincie, Rijk.

**Comment by lvdbrink** [comment]
Als commentaar gemeld in consultatie EMSO.
