### ISSUE TITLE
Afstemming met NEN 2660

### ISSUE THREAD

**Issue by mickbaggen** [Geonovum/disgeo-imsor#41]
In de Modelleerprincipes wordt verwezen naar de oude versie van de NEN 2660 uit 1996. Deze is helaas niet meer bij de tijd, en voegt geen relevante, of zelfs foutieve modelleerprincipes toe. Het is wel mogelijk om te verwijzen naar de Ontw. NEN 2660-1 en Ontw. NEN 2660-2, die tot 1 juli 2021 voor publieke consultatie worden aangeboden via de NEN webshop, NEN Connect en https://normontwerpen.nen.nl. Zie https://normontwerpen.nen.nl/Home/Details/754 (Deel 1) en https://normontwerpen.nen.nl/Home/Details/755 (deel 2). Na sluiting van de publieke consultatie zal de definitieve normtekst binnen een of twee maanden beschikbaar komen. 

In de nieuwe NEN 2660 worden vele onderwerpen geadresseerd die ook in Disgeo/IMSOR aan de orde komen. Dit geldt onder meer voor de definitie van object (#1), levensloop van een object (#15) en netwerken (#40).

**Comment by RiX012** [comment]
Wellicht overlap met #16 ?

**Comment by lvdbrink** [comment]
Dank je wel @mickbaggen, ik heb verwijzingen naar de nieuwe versies opgenomen in de tekst!
