### ISSUE TITLE
Doorlopend - Document dat modelleerprincipes en -uitgangspunten beschrijft

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/disgeo-imsor#5]
We hebben een document nodig dat de principes beschrijft op basis waarvan het modelleerteam haar werk doet. 

Hierin nemen we ook uitgangspunten op, zoals: 
- We modelleren conform MIM 1.1 en NEN3610:2020 (ongepubliceerde versie)
- Daarnaast sluiten we zoveel mogelijk aan op NTA8035.
- ...

Vorm: ReSpec document.

**Comment by lvdbrink** [comment]
Punt vanuit de groep die NEN3610/NEN2660/MIM/NTA8035 aansluiting doet: 

> In de modelleer uitgangspunten mis ik een referentie naar sector standaarden die de overheid verplicht is te gebruiken. Het uitgangspunt in de SOR is dat wij deze sector standaarden goed aansluitbaar maken en geen zaken anders doen. (voorbeeld IMBRO). Dit betekent in dat we zowel bovenliggende standaarden als onderliggende standaarden moeten meenemen in het traject.

Dit is niet alleen een inhoudelijk punt maar ook een modelleertechnisch punt. Hoe zorgen we dat het informatiemodel SOR in technische zin naadloos gaat aansluiten op bestaande sectorstandaarden. Of andersom geformuleerd, hoe zorgen we dat nieuwe of bestaande sectormodellen en organisatie specifieke informatiemodellen naadloos op de SOR aan kunnen sluiten. 

Meer concreet vragen we ons bijvoorbeeld af of we concepten uit sectorstandaarden, voor zover die al op een publieke URI gepubliceerd zijn, gaan dupliceren, waarbij we verklaren dat de concepten equivalent zijn; of dat we waar mogelijk rechtstreeks naar concepten uit sectorstandaarden gaan verwijzen. 

Een andere vraag die sectorstandaarden kan raken is wanneer maak je van iets een klasse, en wanneer volsta je met een term + definitie in een waardelijst. 

Dit zou een meer concrete uitbreiding van U1 kunnen zijn. Iets als "_Gestandaardiseerde sectorale informatiemodellen, en organisatiespecifieke informatiemodellen, kunnen naadloos worden gekoppeld aan het informatiemodel van de SOR_".

**Comment by RiX012** [comment]
> Meer concreet vragen we ons bijvoorbeeld af of we concepten uit sectorstandaarden, voor zover die al op een publieke URI gepubliceerd zijn, gaan dupliceren, waarbij we verklaren dat de concepten equivalent zijn; of dat we waar mogelijk rechtstreeks naar concepten uit sectorstandaarden gaan verwijzen.

Dit is een heel belangrijk punt waar momenteel iedereen heel erg mee worstelt. In de loop van de tijd is gebleken dat het technisch niet eens heel ingewikkeld is, maar dat de governance het meest lastige is. Geonovum (jullie) heeft dat [hier][1] al eens mooi beschreven. Dit punt wil ik graag over meedenken, omdat ik zelf ook al de nodige best practices en uitdagingen hierop verzameld heb. Michel Bohms heeft hier voor de OTL Amsterdam vs IMBOR-LD twee technische voorbeelden uitgewerkt in OWL en SHACL.

[1]: https://docs.geostandaarden.nl/disgeo/dll/#governance-op-het-snijvlak

**Comment by lvdbrink** [comment]
In de nieuwe consultatieversie van [DiS Geo: Architectuurbeschrijving Voorzieningen Samenhangende Objectenregistratie](https://docs.geostandaarden.nl/disgeo/cv-al-arch-20201115/) staan een aantal zaken die wellicht in een of andere vorm kunnen meenemen in de modelleerprincipes en -uitgangspunten. Sommige punten hebben we ook al benoemd.

Uit 2.1, over het doel van de samenhangende objectregistratie (al deze punten, komen uit de beleidsvisie):

> _	Een betrouwbare, consistente en actuele samenhangende gegevensset voor heel Nederland;
> -	Een efficiëntere inwinning en bijhouding van objecten, ook in drie dimensies (3D);
> -	Een betere inpassing in moderne architecturen;
> -	Meer en eenvoudiger gebruik van deze informatie in maatschappelijke toepassingen. De registratie gedraagt zich voor de gebruiker als één registratie.
> -	De objectenregistratie maakt onderdeel uit van een robuuste geo-informatie infrastructuur binnen de generieke digitale infrastructuur en voldoet aan de 12 eisen voor een basisregistratie

Wat betreft die laatste, voor ons is vooral relevant: 

> Eis 11: De positie van de basisregistratie binnen het stelsel van basisregistraties is duidelijk en de relaties met de basisregistraties zijn beschreven

> Er zijn duidelijke afspraken over de afbakening, aanduiding en de relaties van de gegevens binnen het stelsel van basisregistraties. Ook bij het toevoegen van een nieuwe basisregistratie. Zo is en blijft het stelsel intern consistent.

Uit hfd 3, Inrichtingsprincipes, 3.1: 

> -	Gegevens passen bij elkaar: relaties tussen gegevens zijn voor gebruikers duidelijk, en gegevens zijn in samenhang bruikbaar
> -	De gegevensstructuur kan snel genoeg meegroeien met de gebruiksbehoefte
> -	In het ontwerp van een samenhangende objectenregistratie is sprake van een nadrukkelijke scheiding tussen de vastlegging van gegevens en de functionaliteit voor het bewerken, opvragen en presenteren daarvan.
> -	Keuzen voor een technische inrichting van de registratie worden pas later in het traject gemaakt, zodat oplossingen gebaseerd zijn op recente inzichten in oplossingsmogelijkheden.
> -	Vanuit andere (basis)registraties, zoals de subjectenregistraties BRP of HR, moeten eenvoudig relaties gelegd kunnen worden naar de samenhangende objectenregistratie.
> -	De registratie gedraagt zich voor gebruikers zoveel mogelijk als één registratie, of het daadwerkelijk één registratie wordt, is nog niet bepaald (nader uit te werken). Daarnaast kunnen er uit de registratie (informatie)producten afgeleid worden en beschikbaar gesteld worden.

Uit 3.3 ICT-inrichtingsprincipes:

> -	Dataservices leggen het creeren, wijzingen en raadplegen van gegevens vast in logging, zodat deze services ervoor kunnen zorgen dat aantoonbaar is wat door gemachtigde leveranciers onder verantwoordelijkheid van bronhouders plaatsvindt. Alle transacties op de gegevens worden gelogd. Dit is nodig om een audit-trail te kunnen opbouwen.
> -	Inrichtingsprincipe 4: Data wordt op betrouwbare en veilige wijze ontsloten, zodat aangetoond kan worden dat data niet bedoeld of onbedoeld gemanipuleerd is. Om op data te kunnen vertrouwen zorgen functies ervoor dat data bij alle handelingen vanaf het moment van ontstaan tot het moment van gebruik veilig is. Data wijzigt daarom alleen op basis van een brondocument of mutatieverwijzing en de wijziging wordt vastgelegd. Integriteit en consistentie van data wordt bewaakt. Data wordt bewaard conform de eisen van de wet (w.o. archiefwet, etc.).
> -	Inrichtingsprincipe 5: Samenhangend gebruik van data is makkelijk mogelijk, zodat data uit verschillende gegevensverzamelingen te combineren is. Het is mogelijk dat er samengestelde producten over het geheel van het gegevenslandschap kunnen worden gerealiseerd.

**Comment by lvdbrink** [comment]
Het modelleerprincipes document is in ruwe vorm af. Er zijn een paar open issues naar aanleiding waarvan nog tekst wordt toegevoegd aan het document. Daarna review door expertgroep. 

De open issues zijn #1 en #3. Dit overkoepelende issue sluit ik bij deze.
