### ISSUE TITLE
Inventarisatie van metadata aspecten

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/disgeo-imsor#60]
We hebben een inventarisatie nodig van de verschillende metadata aspecten die een rol spelen in de SOR om alle aspecten van metadata goed te kunnen plaatsen (het gaat om metadata op verschillende niveaus) te definieren, en goed te kunnen modelleren i.e. een standaard patroon voor metadata kunnen beschrijven. 

De definitie van metadata in de [modelleerprincipes](https://geonovum.github.io/disgeo-imsor/modelleerprincipes/) moet breder, om recht te doen aan het bestaan van metadata op allerlei niveaus. We willen alle soorten metadata die we hanteren van een definitie voorzien.  Daarvoor hebben we deze inventarisatie nodig. Eind vorig jaar hebben we al een overzichtsdiagram gemaakt van de metadata niveaus. Dit gaan we actualiseren. 

Om metadata goed te kunnen modelleren hebben we ook een inventarisatie nodig van bestaande standaarden die metadata-aspecten beschrijven. Deze standaarden koppelen we aan de verschillende metadata niveaus die we onderscheiden. 

Doen: 
- excel bestand maken met overzicht van de metadata aspecten, gebaseerd op EMSO
- diagram met metadata niveaus updaten en speigelen tegen de in EMSO gevonden metadata aspecten
- inventarisatie maken (in zelfde excel bestand) van metadata standaarden en deze relateren aan de metadata niveaus

(De definitie van 'metadata' [op verschillende niveaus] in de modelleerprincipes komt hierna in een apart issue)

**Comment by lvdbrink** [comment]
Er staat al een eerste inventarisatie van metadata standaarden in [inventarisatie_metadata_sor.xlsx](https://github.com/Geonovum/disgeo-imsor/blob/master/issues/60-metadata/inventarisatie_metadata_sor.xlsx). 

Deze nog aanvullen met 
- ISO 19110: Geographic information - Methodology for feature cataloguing

En mogelijk ook: 
- schema.org, maar dit lijkt me meer een bron voor begrippen waaruit je bv kan putten als je keywords wil toevoegen, dan dat het een metadata standaard is;
- OGC API Records, hoewel dit gaat over interfaces, niet over data(sets); 
- ISO 19119, hoewel dit gaat over metadata voor services, niet over data(sets).

**Comment by lvdbrink** [comment]
Voor ISO 19119 zie https://docs.geostandaarden.nl/md/mdprofiel-iso19119/

**Comment by lvdbrink** [comment]
Werkverdeling met Gabriella afgesproken: 

- ISO 19110 is nvt? Gabriella bespreekt dit met Ine.
- PROV-O inventarisatie > Linda
- DQV  inventarisatie > Gabriella
- metadata framework aanvullen obv aantekeningen gesprek 15-7 > Linda (ook kijken naar wat MIM zegt over overerving van metadata aspecten, om de hoofdgroepen te kunnen beschrijven)
- NORA gegevenskwaliteit bekijken > Gabriella
- 	vergelijken met ISO 19157 
- 	vergelijken met  de DisGeo eisen aan inhoud mbt metadata 
- vergelijking met inventarisatie van Arnoud en Silvy > Gabriella
- diagram updaten > doen we later
- kijken naar inhoudelijke hoofdstukken van emso voor meer eisen > Linda

**Comment by lvdbrink** [comment]
Wat MIM zegt over overerving van metadata aspecten, om de hoofdgroepen te kunnen beschrijven:
> de metadata aspecten zijn specifiek voor elk modelelement apart. Dus als er in H2.2 sprake is van een generalisatie, dan worden deze metadata niet overerft (en de ingevulde waardes worden uiteraard zeker niet overerft).

We kunnen dus in het formele, MIM conforme informatiemodel aspecten zoals bv de normkwaliteit niet beschrijven bij Bestuurlijk gebied en dit dan laten gelden voor alle subklassen van Bestuurlijk gebied. Ik heb hier een Note voor opgenomen in het framework.

**Comment by gabswiersma** [comment]
Eerder vandaag heb ik met Ine gesproken over de toepassing van ISO 19110: het is bedoeld voor het beschrijven van een objectencatalogus (feature catalogue). In het Nationaal Georegister wordt deze ISO gebruikt om een overzicht te geven van objecttypes en hun eigenschappen in een dataset.

Het idee erachter is dus om een gestructureerde, machine-leesbare beschrijving van object types te ontsluiten die je vervolgens ook makkelijk in tekst/tabellen zou kunnen vertalen.  In ISO 19131 (voor het beschrijven van data product specificaties - zoals inwinningsregels, bijhouding, data kwaliteit, etc)  wordt ook gezegd dat een eventuele feature catalogue conform ISO 19110 moet zijn. 

Echter passen wij MIM toe in het kader van de SOR, waarmee een soortgelijke beschrijving gegenereerd kan worden vanuit het UML model (middels Imvertor). De vraag is of zo'n catalogus conform 19110 is opgesteld - en zo niet, wat zijn de consequenties voor ons? Het lijkt mij goed om stil te staan bij deze vraag, aangezien we nu ook naar gerelateerde ISO standaarden kijken (19157, 19131, 19115). 
In de (conceptversie van) NEN3610 wordt bijvoorbeeld een opmerking gemaakt over conformance bij het opstellen van een catalogus (in C.3.3.2.c):

> Er is in NEN 3610 geen regel opgenomen voor het gebruik van een objectcatalogus in een dataspecificatie. Conformiteit met de ISO normen impliceert deze test.

Ik zou denken dat we aan de ISO 19110 kunnen voldoen als we MIM toepassen, maar het is goed om dit na te gaan.

**Comment by gabswiersma** [comment]
Ook handig om te weten: er loopt een onderzoek over metadata ontwikkelingen/behoeften in samenwerking met PDOK, daar komt dit onderwerp waarschijnlijk ook aan bod. Het onderzoek loopt nu nog, maar ze hopen een adviesrapport te kunnen publiceren tegen het einde van 2021.
