### ISSUE TITLE
Vergelijking MIM / NEN3610 / NTA8035

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/disgeo-imsor#7]
MIM 1.1 en NEN3610:2020 zijn voor ons uitgangspunten waar we ons aan moeten houden. NTA8035 moeten we zo veel als mogeljik volgen. Daarom is het nodig om deze drie standaarden met elkaar te vergelijken. 

Waar er verschillen zijn, die voor ons bij het modelleren binnen DisGeo problemen of onduidelijkheden opleveren, maken we (zoveel mogelijk in overleg met vertegenwoordigers van MIM/NEN3610/NTA8035) beargumenteerde keuzes over hoe hier mee om te gaan in het IMSOR. Deze keuzes worden uiteindelijk opgenomen in de modelleerprincipes. De verschillenanalyse wordt in eerste instantie gedocumenteerd in het ReSpec document over modelleerprincipes.

Voorbeelden van verschillen die we al geconstateerd hebben:
- MIM maakt onderscheid tussen (abstracte) concepten enerzijds en klassen van dingen anderszijds, terwijl NTA dat niet doet. We kunnen niet SKOS toepassen zoals NTA dat doet.
- NTA heeft een toplevel model, MIM niet.
- Bij NEN lijkt een fysiek object te worden gelijkgesteld met zijn geometrische representatie, bij NTA niet.

**Comment by lvdbrink** [comment]
@gabswiersma doet laatste aanvullingen
Daarna leest @lvdbrink het door, schrijft er een voorwoord bij en stuurt het naar de NEN3610-NEN2660-MIM groep.

**Comment by lvdbrink** [comment]
Ik heb de analyse aangevuld en opgestuurd naar de mensen van Geonovum, RWS en TNO die zich bezig houden met de afstemming van MIM, NEN3610 en NTA8035/ISO2660 deel 1 en 2. 

Woensdag even afstemmen of we dit issue kunnen sluiten.

**Comment by lvdbrink** [comment]
> Bij NEN lijkt een fysiek object te worden gelijkgesteld met zijn geometrische representatie, bij NTA niet.

Reactie Remco in 't Hout: Alle objecttypen in de NEN 3610, dus zowel fysiek (reëel) als virtueel, vervullen binnen deze context de rol van geo-object. NEN3610 beschouwd immers objecttypen waarbij locatie-informatie van belang is. In andere contexten kunnen deze objecttypen echter ook gebruikt worden. De definities hangen namelijk niet af van de locatie of geometrische representatie.
Ik probeer overigens de meest recente versie van de NTA 8035 te downloaden na het bestelproces te hebben doorlopen, maar krijg steeds een foutmelding (pdf wordt niet gevonden).

**Comment by lvdbrink** [comment]
Nog een week open houden voor reacties.

**Comment by RiX012** [comment]
- **Geo-object**. NEN3610 noemt het een abstractie. Misschien is 'representatie' beter op zijn plek. Om dit ook naar 3D-object te zetten.
- **fysiek object**. In de NTA8035 wordt naar mijn mening met _virtueel object_ bedoelt dat een fysiek object ook kan bestaan in gedachten of op tekening. Als ik de lantaarnpaal bij mij om de hoek in mijn gedachte heb, heb ik de virtuele representatie in mijn gedachte van die specifieke lantaarnpaal. Hetzelfde geldt voor de punt op de kaart, die virtueel dat specifieke fysiek object representeert.
- **virtueel object**. Het gaat dus niet alleen om 'registratief gebied' o.i.d. maar ook om virtuele representaties van fysieke objecten of registratieve gebieden.
- **functioneel object**. Ik denk dat er geen verschil zit tussen het NTA8035 Functioneel object en het NEN3610 functie object. Misschien wel goed om hetgeen wat in de SMLS onder de Systems engineering extension staat eens te raadplegen. Bij Michel Bohms verkrijgbaar.
-  **individu**. Ik vraag me af of de conclusie over individu klopt. In de NTA wordt bedoeld dat er maar één aanwijsbaar (en uiteraard ook weer in gedachte mogelijk) exemplaar van is. Het verschil tussen ObjectType de instantie 'Object' als het ware.

**Comment by RiX012** [comment]
Goede vergelijking gemaakt van de terminologie. Geeft duidelijk aan dat er behoorlijk wat verschil in semantiek zit. Maar is een vergelijking om terminologie genoeg? Alle drie geven ook richtlijnen voor modelleerprincipes en modelleerconstructies. Daarnaast worden er ook interpretaties gedaan voor de LinkedData toepassing. Ik denk dat hier ook nog wel verschillen in zitten. Staat dit ook nog op de planning om hier in te duiken?

**Comment by pmaria** [comment]
@RiX012 alvast een reactie op een paar van je punten:

> * __fysiek object__. In de NTA8035 wordt naar mijn mening met virtueel object bedoelt dat een fysiek object ook kan bestaan in gedachten of op tekening. Als ik de lantaarnpaal bij mij om de hoek in mijn gedachte heb, heb ik de virtuele representatie in mijn gedachte van die specifieke lantaarnpaal. Hetzelfde geldt voor de punt op de kaart, die virtueel dat specifieke fysiek object representeert.

de NTA zegt ook over fysiek en virtueel object:
> Een zelfde fysiek object kan zowel virtueel bestaan, bijvoorbeeld op een tekening of in de vorm van een digitaal model, en in de werkelijke wereld (geconstrueerd en in gebruik). Het betreft hier de verschillende __levenscycli__ waarin een object kan verkeren.

Uit de eerste zin zou je dat kunnen concluderen, echter met de tweede zin over levenscycli lijkt weer iets anders bedoeld te worden.


> * __individu__. Ik vraag me af of de conclusie over individu klopt. In de NTA wordt bedoeld dat er maar één aanwijsbaar (en uiteraard ook weer in gedachte mogelijk) exemplaar van is. Het verschil tussen ObjectType de instantie 'Object' als het ware.

Goed punt. 'Individu' is wel wat we willen dat 'Object' betekent, om de samenhangende objectenregistratie te realiseren. Dat kan namelijk alleen wanneer bij het vastleggen van informatie over hetzelfde individu, we weten dat we het over hetzelfde individu hebben en we informatie zo vastleggen dat anderen die het individu kennen het ook kunnen begrijpen.


> Goede vergelijking gemaakt van de terminologie. Geeft duidelijk aan dat er behoorlijk wat verschil in semantiek zit. Maar is een vergelijking om terminologie genoeg? Alle drie geven ook richtlijnen voor modelleerprincipes en modelleerconstructies. Daarnaast worden er ook interpretaties gedaan voor de LinkedData toepassing. Ik denk dat hier ook nog wel verschillen in zitten. Staat dit ook nog op de planning om hier in te duiken?

Zeker. Het eerste idee was om die vergelijking te doen bij het opstellen van het metamodel voor IMSOR. Maar, misschien is het ook beter om het naar voren te trekken. Ik ben er nog niet helemaal over uit.

**Comment by RiX012** [comment]
> Uit de eerste zin zou je dat kunnen concluderen, echter met de tweede zin over levenscycli lijkt weer iets anders bedoeld te worden.

Ik interpreteer dit als AsRequired, AsDesigned, AsEngineerd, AsBuilt, etc. Ik ben met je eens dat dit verwarring oplevert. Zou goed zijn om Michel Bohms hier eens opheldering te vragen.


> Zeker. Het eerste idee was om die vergelijking te doen bij het opstellen van het metamodel voor IMSOR. Maar, misschien is het ook beter om het naar voren te trekken. Ik ben er nog niet helemaal over uit.

Ok. Ik denk dat dat wel een uitdaging is. Ik probeer zelf IMBOR te modelleren volgens MIM en tevens de NTA8035, maar dat valt qua modelleringsprincipes nog niet mee.

**Comment by lvdbrink** [comment]
Ik sluit het issue omdat het eerste deel van de vergelijking, de terminologie, afgerond is. 

Vervolgissue #17 aangemaakt om verder te werken aan de vergelijking van modelleerprincipes en -constructies in de desbetreffende standaarden.
